Scorrere in basso per avere i log piu' recenti.
I Log vengono registrati ogni volta che viene lanciato il programma.


I seguenti Log fanno riferimento al giorno 26-10-2020 alle ore 12.05.45

Ho letto l'excel: C:/Users/Ali Haider Maqsood/Documents/GitHub/MAW/RinominaPdf/rinomina.xlsx
Colonna attuale letta con successo!
Colonna nuovo letta con successo!

Cerco di rinominare il file nuovo1.pdf con nuovo1111.pdf
Errore nel rinominare il file nuovo1.pdf che dovrebbe essere nella directory C:/Users/Ali Haider Maqsood/Documents/GitHub/MAW/RinominaPdf/
Errore: Traceback (most recent call last):
  File "RinominarePdfDaInput.py", line 36, in <module>
    os.rename(directory + fileAttuale + tipoFile, directory + valori_new[indice_new] + tipoFile)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'C:/Users/Ali Haider Maqsood/Documents/GitHub/MAW/RinominaPdf/nuovo1.pdf' -> 'C:/Users/Ali Haider Maqsood/Documents/GitHub/MAW/RinominaPdf/nuovo1111.pdf'

Cerco di rinominare il file nuovo2.pdf con nuovo2222.pdf
Rinominazione avvenuta con successo!
